name: Deploy DMOJ with Ngrok

on:
  workflow_dispatch: # Cho phép kích hoạt workflow theo yêu cầu.

jobs:
  deploy-dmoj:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git gcc g++ make python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev gettext curl redis-server mariadb-server libmysqlclient-dev \
          supervisor nginx
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install -g sass postcss-cli postcss autoprefixer

    - name: Configure MariaDB
      run: |
        sudo service mariadb start
        sudo mariadb -e "CREATE DATABASE dmoj DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;"
        sudo mariadb -e "GRANT ALL PRIVILEGES ON dmoj.* TO 'dmoj'@'localhost' IDENTIFIED BY 'yourpassword';"
        sudo mariadb-tzinfo-to-sql /usr/share/zoneinfo | sudo mariadb -u root mysql

    - name: Install DMOJ site
      run: |
        python3 -m venv dmojsite
        . dmojsite/bin/activate
        git clone https://github.com/DMOJ/site.git
        cd site
        git submodule init
        git submodule update
        pip3 install -r requirements.txt
        pip3 install mysqlclient

    - name: Configure DMOJ
      run: |
        cp site/dmoj/local_settings.example.py site/dmoj/local_settings.py
        sed -i "s/'USER': 'root',/'USER': 'dmoj',/g" site/dmoj/local_settings.py
        sed -i "s/'PASSWORD': '',/'PASSWORD': 'yourpassword',/g" site/dmoj/local_settings.py
        sed -i "s/'NAME': 'dmoj',/'NAME': 'dmoj',/g" site/dmoj/local_settings.py

    - name: Prepare DMOJ assets and database
      run: |
        . dmojsite/bin/activate
        cd site
        ./make_style.sh
        python3 manage.py collectstatic --no-input
        python3 manage.py compilemessages
        python3 manage.py compilejsi18n
        python3 manage.py migrate
        python3 manage.py loaddata navbar
        python3 manage.py loaddata language_small
        python3 manage.py createsuperuser --username admin --email admin@example.com --no-input
        echo "from django.contrib.auth.models import User; User.objects.filter(username='admin').update(password='pbkdf2_sha256$260000$hash')" | python3 manage.py shell

    - name: Start DMOJ and Ngrok
      run: |
        . dmojsite/bin/activate
        nohup python3 site/manage.py runserver 0.0.0.0:8000 > dmoj.log 2>&1 &
        ngrok authtoken 2nyiyWrhpT6OwyUoaoZ2zdE9nNo_7KtHBQxaox3Wx2t9qBHTT
        ngrok http 8000 --log=stdout > ngrok.log &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Keep the server running
      run: |
        tail -f /dev/null
